version: '3.8'

services:
  truth-engine:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - ollama
    environment:
      - PORT=3000
      - NODE_ENV=production
      - OLLAMA_URL=http://ollama:11434
      - OLLAMA_MODEL=qwen2.5:7b
      - USE_PROXIES=false
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped
    command: serve

volumes:
  ollama_data: